online_petition/config/routes.rb
Rails.application.routes.draw do
  root 'petitions#index_last'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users

  resources :petitions do
    member do
      post 'upvote', to: 'petitions#upvote', as: 'upvote'
    end
  end

  mount Resque::Server, :at => "/resque"

end

online_petition/app/models/petition.rb
class Petition < ActiveRecord::Base
  EXPIRED_PERIOD_DAYS = 30
  WIN_VOTES_NUM = 100

  belongs_to :user
  has_many :votes, dependent: :destroy

  scope :expired, -> { where('created_at < ?', (DateTime.now - EXPIRED_PERIOD_DAYS)) }

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 256 }
  validates :text, presence: true, length: { maximum: 2000 }

  def win?
    self.votes.count >= min_votes_num
  end

  def min_votes_num
    WIN_VOTES_NUM
  end

  def become_expired?
    Petition.expired.include? self
  end
end

online_petition/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :petitions
  has_many :votes, dependent: :destroy

  before_save { self.email = email.downcase }

  validates :first_name, presence: true, length: { maximum: 256 }
  validates :last_name, presence: true, length: { maximum: 256 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 4 }

  def author
    User.find(id = @petition.user_id)
  end
end

online_petition/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :petition
  validates :user_id, presence: true
  validates :petition_id, presence: true
end

online_petition/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :can_vote?

  private

  def can_vote?
    @petition = Petition.find(params[:id])
    author = (@petition.user.id == current_user.id)
    voted = !(@petition.votes.select { |v| v.user_id == current_user.id }.empty?)
    !(author || voted)
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_url, alert: 'Пожалуйста, авторизуйтесь' if current_user.nil?
  end

  def author
    redirect_to root_url, alert: 'Не автор' unless current_user.id == Petition.find(params[:id]).user_id
  end
end

online_petition/app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  before_filter :authorize, only: [:new, :create, :update, :upvote]
  before_filter :author, only: [:edit, :update]

  def index
    if params[:my] && current_user
      @petitions = Petition.where(user_id: current_user.id).reverse
      @title = 'Мои петиции'
    else
      @petitions = Petition.all.reverse
      @title = 'Все петиции'
    end
    @users = User.all
  end

  def index_last
    @petitions = Petition.last(10).reverse
    @users = User.all
    @title = 'Последние петиции'
    render 'index'
  end

  def new
    @petition = Petition.new
  end

  def edit
    @petition = Petition.find(params[:id])
  end

  def destroy
    @petition = Petition.find(params[:id])
    @petition.destroy!
    redirect_to :back, notice: 'Петиция удалена'
  end

  def show
    @petition = Petition.find(params[:id])
  end

  def create
    @petition = Petition.new(petition_params)
    @petition.user_id = current_user.id
    if @petition.save
      redirect_to @petition
    else
      render 'new'
    end
  end

  def update
    @petition = Petition.find(params[:id])
    if @petition.update_attributes(petition_params)
      redirect_to @petition, notice: 'Петиция обновлена'
    else
      render 'edit'
    end
  end

  def upvote
    @vote = Vote.new
    @petition = Petition.find(params[:id])
    if @petition.votes.create(user_id: current_user.id, petition_id: @petition.id).save
      Resque.enqueue(SendEmailJob, @petition.id)
    redirect_to :back, notice: 'Спасибо. Ваш голос был учтен!'
    end
  end

  private

  def petition_params
    params.require(:petition).permit(:title, :text) if params[:petition]
  end
end

online_petition/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    render 'new'
  end

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Добро пожаловать, #{user.email}"
    else
      flash.now.alert = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Вы успешно вышли!'
  end
end

online_petition/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      UserMailer.welcome_email(@user).deliver_now
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end
end

online_petition/app/helpers/application_helper.rb
module ApplicationHelper
end

online_petition/app/helpers/petitions_controller_helper.rb
module PetitionsControllerHelper
end

online_petition/app/helpers/sessions_controller_helper.rb
module SessionsControllerHelper
end

online_petition/app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

online_petition/app/helpers/welcome_helper.rb
module WelcomeHelper
end

online_petition/app/views/application/_footer.html.erb
<footer>
  <span>© Company 2016</span>
</footer>

online_petition/app/views/application/_header.html.erb
  <div class="col-md-12">
    <!-- BEGIN logo -->
    <div class="col-md-9">
     <span class="logo">
       <%= link_to 'Онлайн петиции нашего района', root_path%>
     </span>
    </div>
    <!-- END logo -->

    <!-- BEGIN user info -->
    <div class="col-md-3 user-options">
      <span>
    <% if current_user %>
          <%= current_user.email %> (<%= link_to 'Выйти', logout_path%>)
      <% else %>
          <%= link_to 'Зарегистрироваться',signup_path %> | <%= link_to 'Войти', login_path %>
      <% end %>
        </span>
     </div>
    <!-- END user info -->
  </div>

online_petition/app/views/application/_links_menu.html.erb
<!-- BEGIN menu -->
<div class="well sidebar-nav">
  <ul class="nav nav-list menu-links">
    <li><%= link_to 'Все петиции', petitions_path %></li>
    <li><%= link_to 'Создать петицию', new_petition_path %></li>
    <% if current_user %>
        <li><%= link_to 'Мои петиции', petitions_path({ my: true } ) %></li>
    <% end %>
  </ul>
</div>
<!-- END menu -->

online_petition/app/views/application/_my_petitions_table.html.erb
<!-- BEGIN table with current user petitions -->
<table class="table">
  <thead>
  <tr>
    <th>Петиция</th>
    <th>Голоса</th>
    <th>Дата создания</th>
    <th colspan="2" style="text-align:center;">Мои действия</th>
  </tr>
  </thead>

  <% @petitions.each do |petition| %>
    <tr>
      <td>
        <%= link_to petition.title, petition_path(petition)%>
      </td>
      <td><%= petition.votes.count %></td>
      <td><%= petition.updated_at.strftime("%d/%m/%Y %I:%M")%></td>
      <td  style="text-align:center;"><%= link_to :Изменить, edit_petition_path(petition)%></td>
      <td  style="text-align:center;"><%= link_to :Удалить, petition_path(petition), method: :delete %></td>
    </tr>
  <% end %>
</table>
<!-- END table with current user petitions -->

online_petition/app/views/application/_petitions_table.html.erb
<!-- BEGIN table with all petitions -->
<table class="table">
  <thead>
  <tr>
    <th>Петиция</th>
    <th>Автор</th>
    <th>Голоса</th>
    <th>Дата создания</th>
  </tr>
  </thead>

  <% @petitions.each do |petition| %>
      <tr>
      <td>
        <%= link_to petition.title, petition_path(petition)%>
      </td>
      <td>
        <% user = @users.find(id=petition.user_id) %>
        <%= [user.first_name, user.last_name].join(' ') %>
      </td>
      <td><%= petition.votes.count %></td>
      <td><%= petition.updated_at.strftime("%d/%m/%Y %I:%M")%></td>
      </tr>
  <% end %>
</table>
<!-- END table with all petitions -->

online_petition/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlinePetition</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- BEGIN header -->
<div class="col-md-12 well sidebar-nav header">
  <%= render partial: "header" %>
</div>
<!-- END header -->

<!-- BEGIN main container -->
<div class="col-md-12">

  <!-- BEGIN content -->
  <div class="col-md-9">
    <%= yield %>
  </div>
<!-- END content -->

  <!-- BEGIN menu -->
  <div class="col-md-3">
    <%= render partial: "links_menu" %>
  </div>
<!-- END menu -->
</div>
<!-- END main container -->

<!-- BEGIN footer -->
<div class="col-md-12 footer">
  <%= render partial: "footer" %>
</div>
<!-- END footer -->

</body>
</html>

online_petition/app/views/petitions/edit.html.erb
<h1> Редактировать петицию: </h1>
<!-- BEGIN edit petition form -->
    <%= form_for :petition,  url: petition_path(@petition), method: :patch do |f| %>
    <p>
      <%= f.label :Название %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :Описание %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit 'Сохранить', :name => 'update' %>
    </p>
<% end %>
<!-- END edit petition form -->

online_petition/app/views/petitions/index.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-success"><%= msg %></div>
<% end %>

<h1><%= @title %></h1>

<!-- BEGIN table with petitions -->
<% if @title == 'Мои петиции'  %>
    <%= render "my_petitions_table", layout: "application" %>
<% else %>
    <%= render "petitions_table", layout: "application" %>
<% end %>
<!-- END table with petitions -->

online_petition/app/views/petitions/new.html.erb
<h1> Новая петиция </h1>

    <% flash.each do |name, msg| %>
        <div class="alert alert-success"><%= msg %></div>
    <% end %>

<!-- BEGIN new petition form -->
  <%= form_for :petition, url: petitions_path  do |f| %>

    <% if @petition.errors.any? %>
        <% @petition.errors.full_messages.each do |message| %>
            <div class="alert alert-danger">
              <%=  message %>
            </div>
        <% end %>
    <% end %>

      <div class="form-group">
        <%= f.label :title, 'Название' %><br>
        <%= f.text_field :title %>
      </div>

      <div class="form-group">
        <%= f.label :text, 'Описание' %><br>
        <%= f.text_area :text, rows: 10 %>
      </div>
      <%= f.submit 'Создать', :name => 'submit', class: "btn btn-lg btn-success" %>

  <% end %>
<!-- END new petition form -->

online_petition/app/views/petitions/show.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-success"><%= msg %></div>
<% end %>

<h1>Петиция</h1>

<div>
  <!-- BEGIN petition petition block -->
  <%= form_for :petition, url: petitions_path  do |f| %>
    <h3><%= @petition.title %></h3>
      <br>
      <%= @petition.updated_at.strftime("%d/%m/%Y %I:%M") %>
      <div><%= @petition.text %></div>
      <br>
  <!-- END petition block -->
  <!-- BEGIN votes block -->
      <b>Голосов: <%= @petition.votes.count %></b>
      <br>
      <% unless @petition.win? || @petition.become_expired?  %>
          <% case  %>
          <% when current_user && can_vote? %>
            <%= link_to 'Поддержать', upvote_petition_path(@petition), :method=>:post, class: "btn btn-primary btn-large" %>
            <% when current_user && !can_vote? && (current_user.id == @petition.user_id) %>
            <% when current_user && !can_vote?  %>
                Вы уже поддержали данную петицию
          <% end %>
      <% end %>
  <!-- BEGIN votes block -->
      <br>
  <% end %>
</div>

online_petition/app/views/users/index.html.erb
<!-- BEGIN users page -->
<!-- END users page -->

online_petition/app/views/users/new.html.erb
<div class="col-md-6">
  <h1>Регистрация</h1>
  <!-- BEGIN sign up form -->
  <%= form_for :user, url: users_path  do |f| %>
      <% if @user.errors.any? %>
          <% @user.errors.full_messages.each do |message| %>
              <div class="label label-danger">
                <%=  message %>
              </div>
          <% end %>
      <% end %>

      <div class="form-group">
        <%=  f.label :email, 'Email' %>
        <%=  f.text_field :email, class: "form-control"  %>
      </div>

      <div class="form-group">
        <%=  f.label :first_name, 'Имя' %>
        <%=  f.text_field :first_name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%=  f.label :last_name, 'Фамилия' %>
        <%=  f.text_field :last_name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Пароль'   %>
        <%= f.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group">
        <%=  f.label :password_confirmation, 'Подтверждение пароля' %>
        <%=  f.password_field :password_confirmation, class: "form-control"%>
      </div>

      <%= f.submit 'Зарегистрироваться', name: 'submit', class: "btn btn-lg btn-primary" %>
  <% end %>
  <!-- END sign up form -->
</div>